### ISSUE TITLE
Возможно, стоит разделить контроллер на несколько, тогда и сервисы у вас будут нести меньше нагрузки

### ISSUE THREAD

**Issue by coursar** [mcarov/spring-mvc-test#10]
Сейчас получился один большой сервис на все фильмы, жанры и т.д.

**Comment by mcarov** [comment]
Может просто сервис разделить тогда, а контроллер не трогать? Там же всего несколько компактных методов и сразу все маппинги видно, и понятно, какой метод за что отвечает.

**Comment by coursar** [comment]
Как вариант, но могут привязаться, "что контроллер знает слишком много".
