### ISSUE TITLE
Потенциально опасно, если вы не кэшируете это значение при запуске приложения, то потом можно установить любое

### ISSUE THREAD

**Issue by coursar** [mcarov/spring-mvc-test#7]
https://github.com/mcarov/spring-mvc-test/blob/15ab7670eea9ee1290b4df521e7d349b1955b9cd/src/main/java/ru/itpark/Constants.java#L4

**Comment by mcarov** [comment]
А как предпочтительнее сделать? Просто в private final этот путь засунуть?

**Comment by coursar** [comment]
@Value("${name}") - для переменных окружения тоже работает

**Comment by coursar** [comment]
В Spring Boot

**Comment by coursar** [comment]
А так - надо в сервисе один раз вытаскивать просто при инициализации и пусть там в final поле хранится
